stages:
  - compile
  - data
  - pkginfo
  - control
  - apk

compile:
  stage: compile
  image: golang:latest
  # cache:
  #   paths:
  #     - .go/pkg/mod/
  # variables:
  #   GOPATH: $CI_PROJECT_DIR/.go
  script:
    # - mkdir -p .go
    - make execvm
  artifacts:
    paths:
      - execvm

data:
  stage: data
  image: islandora/abuild
  script:
    - make data.tar.gz
  artifacts:
    paths:
      - data.tar.gz

pkginfo:
  stage: pkginfo
  image:
    name: hairyhenderson/gomplate:alpine
    entrypoint: [""]
  script:
    - gomplate
  artifacts:
    paths:
      - .PKGINFO

control:
  stage: control
  image: islandora/abuild
  script:
    - make control.tar.gz
  artifacts:
    paths:
      - control.tar.gz

apk:
  stage: apk
  image: islandora/abuild
  script:
    - cat control.tar.gz data.tar.gz > execvm-latest.apk
  artifacts:
    paths:
      - execvm-latest.apk

# openssl genrsa -out emailaddress.priv 2048
# openssl rsa -in emailaddress.priv -pubout -out /etc/apk/keys/emailaddress
